AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ssl-rating-to-slack
    Description: SAM Template that allow you to performs a deep analysis of the configuration of any SSL web server on the public Internet. By using SSL Labs APIs and send results to slack
    Author: devops-made-easy
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['devops-made-easy', "ssl-rating", "ssl-grade", "ssl-labs", "qualys"]
    HomePageUrl: https://github.com/devops-made-easy/aws-sam-ssllabs
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/devops-made-easy/aws-sam-ssllabs


Globals:
  Function:
    Timeout: 300
       
Parameters:
  DomainName:
    Description: "Domain name that needs to be scanned and is publicly accessible"
    Type: String
  SlackWebhookUrl:
    Description: "Your Slack webhook URL "
    Type: String
  CronSchedule:
    Description: "Cron or Rate Expression for cloud watch event  "
    Type: String
    #Default: "cron(0 8 1 * ? *)"


Resources:
  SSLCertificateRating:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ssl_certificate_rating/
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          DOMAIN:
            Ref: DomainName
          SLACK_WEBHOOK_URL:
            Ref: SlackWebhookUrl
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: 
              Ref: CronSchedule
Outputs:
  SSLCertificateRatingFunction:
    Description: "SSLCertificateRating Lambda Function ARN"
    Value: !GetAtt SSLCertificateRating.Arn

